### ISSUE TITLE
a better maintained alternative `klick`

### ISSUE THREAD

**Issue by osdevisnot** [jxnblk/cxs#113]
Aloha @jxnblk 👋

First off, thanks a lot for putting your ideas together in `cxs`. In a lot of ways, this package powers some of the nice UI abstractions I am building recently.

However, looking at #98, it seems `cxs` is not going to be maintained in future. Considering some users (like myself) might still be interested in a small size package that satisfies their styling needs, I started working on a forked version of `cxs` in [**klick**](https://github.com/osdevisnot/klick)

While [`klick`](https://github.com/osdevisnot/klick), attempts to abstract lot of other things (vdom, state container, etc.), the relevant code for styling solution is [here](https://github.com/osdevisnot/klick/blob/master/src/css.tsx). In general, the dist bundle for [`klick`](https://github.com/osdevisnot/klick) is tree-shakable, so other features shouldn't be taxing while importing `css` from [`klick`](https://github.com/osdevisnot/klick)

Few areas [`klick`](https://github.com/osdevisnot/klick) differs from `cxs`
- `klick` uses auto incrementing atomic classnames. I've found this to be generating much smaller class names. Specially helpful in SSR scenarios.
- css portion of `klick` is framework agnostic. We support all frameworks by supporting none.
- No dynamic component styling yet - considering [`klick`](https://github.com/osdevisnot/klick) attempts to be framework agnostic, it does not have dynamic component styling yet. This is however on my roadmap.

Please feel free to close this issue if it seems irrelevant for this repo. I just wanted to get the word out.

**Comment by AlexGalays** [comment]
Or is it? :D

**Comment by osdevisnot** [comment]
Not anymore, I've been pretty happy with goober these days.
