### ISSUE TITLE
transpile pain pile

### ISSUE THREAD

**Issue by kristoferjoseph** [jxnblk/cxs#13]
`var cxs = require('cxs').default`
Otherwise folks who write JavaScript get an error:
> csx is not a function

**Comment by jxnblk** [comment]
Is this a suggestion for non Babel usage/pre-node-6?

**Comment by kristoferjoseph** [comment]
Maybe just a note in the usage docs would suffice. 

I am personally having a knee jerk reaction to trasnpiling, but documenting how to use it with vanilla JS & require would be nice for others who are not riding as bloody an edge.

**Comment by kristoferjoseph** [comment]
Curious though, are you super attached to Babel?

Trying to get a feel for the climate.

**Comment by yoshuawuyts** [comment]
> I am personally having a knee jerk reaction to trasnpiling

Aye same, I don't like having to download half a gig of dependencies to get stuff running. I also don't run `babel` for my Node code (had to debug it before, never doing that again), which means that `cxs` cannot run on the server - which isn't, like, great.

At this point it's not even sure `import` will even make it to Node so yeah, having `import` float around isn't great for people like me that haven't hopped on the `babel` train 🙁

**Comment by jxnblk** [comment]
Why doesn't it work in node for you? It compiles on prepublish...

**Comment by jxnblk** [comment]
@kristoferjoseph as far as working in the browser, you still need something to bundle npm packages to use this, correct? are you not using anything to transpile client-side?

**Comment by kristoferjoseph** [comment]
I am bundling with browserify, but that is it. 

My first experience with cxs was it throwing an error. If I didn't have import battle scars I would have thought cxs was borked. Instead I knew to tack on .default to the require call.

**Comment by yoshuawuyts** [comment]
@jxnblk ah my bad, apologies - I presumed you had `babelify` as a transform - this should be less of an issue then

**Comment by jxnblk** [comment]
I think adding a browserify note to the readme makes sense though, thanks for pointing that out. And personally, I do feel sorta similarly to you two, but still holding out hope on the import syntax, which would make the source code 100% standards-based when that is finalized.

**Comment by kristoferjoseph** [comment]
Thanks. I have 0️⃣ faith in `import` making it. 
The simple fact that it breaks existing code with the `.default` is enough for me to give it the "aw hell naw"

I have a fork of cxs that I am going to back port to code that runs today and not in a possible alternate future timeline.

With that said, I will also be your first homie to update the code when/if `import` lands 💖

**Comment by meyer** [comment]
@kristoferjoseph `import` is not to blame here. [CommonJS default export behaviour was removed in Babel 6][rip]. Package maintainers can add that behaviour back in with [a simple Babel plugin][p].

[rip]: https://phabricator.babeljs.io/T2212
[p]: https://github.com/59naga/babel-plugin-add-module-exports

**Comment by jxnblk** [comment]
Seems like the PR in #15 unfortunately didn't work as-is. I've added a note to the readme, but feel free to open PRs with suggestions for how to handle this better
