### ISSUE TITLE
Common declarations causes unexpected rule conflicts

### ISSUE THREAD

**Issue by Silverwolf90** [jxnblk/cxs#19]
Still having some issues despite my recent PR. If I comment out all the common declarations, all my styles work flawlessly.

**Comment by Silverwolf90** [comment]
It actually seems to me that extracting out common declarations is a very unsafe transformation. For example, if you take a series of cascading media queries each with a different `display` property, then the order in which these display properties occur is essential. However, if the declarations are extracted out and placed in a different order, you'll get bad results.

**Comment by jxnblk** [comment]
Is this still an issue since it's not pulling out nested declarations?
