### ISSUE TITLE
Add benchmarking

### ISSUE THREAD

**Issue by johnotander** [jxnblk/cxs#2]

**Comment by tiagojsalmeida** [comment]
https://github.com/PepijnSenders/css-in-js-perf-tests

**Comment by asilvas** [comment]
It isn't clear to me why jss is so much faster as they both are having to do similar tasks.

**Comment by lachlanjc** [comment]
This is done ✅

**Comment by lachlanjc** [comment]
This is done ✅ cc @jxnblk
