### ISSUE TITLE
Why hash if using singleton styles?

### ISSUE THREAD

**Issue by asilvas** [jxnblk/cxs#25]
You're using a global cache & stylesheet, so why bother including a hash dependency when you control collisions anyway. Your cache is already a hash table, so you could simply use an auto-incrementing global index (ala `cxs-{idx}`). An (small) additional benefit beyond the reduced bytes from hash dependency would be the reduced bytes per class name. You could even reset the index via your reset method, for consistent class names when server-side rendering.

Am I missing something?

Great module!!

**Comment by jxnblk** [comment]
I might not be thinking about this the right way, but I wanted the consistent hashing to help ensure server-side rendering "just works", without the need to match up the indices or identifiers. This also helps dedupe style objects that are identical.

I do like the idea of fewer dependencies, but i'm not sure I understand how the global index thing would work in practice.

**Comment by asilvas** [comment]
Server-side rendering requires a reset either way. The point is you have a singleton cache, which use to be a hashtable, but assuming it was a hashtable you'd just do a check by the key (`JSON.stringify(style)`), which is consistent with what you do now. Feel free to close if you don't want it to work that way -- just another option to optimize.
