### ISSUE TITLE
CSS animations

### ISSUE THREAD

**Issue by tiagojsalmeida** [jxnblk/cxs#46]
Hey guys!
Awesome work on V3, the modes idea is awesome!

I'm having some problems with animations though..
I've tried using `animationName` and `@keyframes` but none are outputing css.

```
cxs({
    animationName: {
        from: {
            background: 'red',
        },
        to: {
            background: 'blue',
        },
    },
});
```

or

```
cxs({
    animationName: 'test',
    '@keyframes test': {
        from: {
            background: 'red',
        },
        to: {
            background: 'blue',
        },
    },
});
```

Can you guys have a look into it?
Thanks in advance!

**Comment by hew** [comment]
@tiagojsalmeida The only mention of keyframes I see is for the `csx-components` option - so keyframes might not be supported for regular `cxs` use.

**Comment by tiagojsalmeida** [comment]
@hew I think they were working before.
Check this PR https://github.com/jxnblk/cxs/pull/12

**Comment by lachlanjc** [comment]
This is done ✅ cc @jxnblk

**Comment by aaronyo** [comment]
@lachlanjc I don't think keyframes are supported. At least, they don't seem to work for me and I don't see any code at the head of master that addresses keyframes.  Am I missing something?

**Comment by tiagojsalmeida** [comment]
This is a year old 👍 
Going to close this issue.
