### ISSUE TITLE
Media Query Grouping of Styles Issue

### ISSUE THREAD

**Issue by crashton28** [jxnblk/cxs#47]
When using the same media query and style between multiple components the styles are grouped into one media query and class name at the point the first component is rendered.  This causes styles in the second component to overwrite the styles used in the media query.  In the following example both buttons should be green when the screen width is above 900px:

http://www.webpackbin.com/VJInpkAHf

**Comment by lukebrooker** [comment]
Yeah, same problem. My first thought that comes to mind is something similar to Styletron where each unique media query should have its own style tag.

**Comment by jxnblk** [comment]
Yeah, I've run into this as well – not sure what the best way to handle this is

**Comment by mihalik** [comment]
I've been working around this issue by adding `!important` to all my media query styles.  I'd like to see a more general solution so I spent a few minutes thinking through some solutions and would like some feedback.  I'd be willing to do the work if we can agree on an acceptable solution.

1.  **`!important` all media query rules**
Similarly to what I've been doing manually, this solves the immediate problem but has many other downsides.  

2. **Media rules are scoped per component**
Not 100% sure how this would be implemented but the idea is that each component's usage of a media rule would get a unique id so it would be placed at the correct place in the stylesheet.  Obviously this would hurt caching.

3. **Media rules all go in a second sheet**
Setup a second (on the page) sheet where all media queries go.  All the existing caching rules would still apply within each sheet.

*All of these solutions make an assumption that it should always be the media query that is overriding the base style.*  Technically with CSS you could order some non media queries after your media queries to override something but I don't think that is a standard pattern, right?  I tried to come up with a reordering solution that would preserve the intended order but could not come up with anything without throwing out caching and scoping all styles to their component.

I like the last option and it seems like a pretty straightforward implementation.  But maybe there is a downside I'm missing?

**Comment by mihalik** [comment]
I've [implemented the media stylesheet](https://github.com/mihalik/cxs/commit/c7e14752b525db9a8a8d178b528bbeeb2f5664ee) in a fork and it seems to work for my needs.  

Let me know if you are interested in a PR.

**Comment by asilvas** [comment]
Media rules should be scoped per parent object. I see no reasonable alternative. 

```
{
  color: blue;
  '@media (min-width: 450px)': {
    color: red;
  }
}
```

Should translate roughly to:

```
{
  color_blue: 'color: blue'
  '{hash_of_parent}_{hash_of_media}_color_red': '@media (min-width: 450px) { color: red; }'
}
```

**Comment by mihalik** [comment]
@asilvas, this is a great suggestion.  I was trying to come up with a good way to scope to a component for my number two above but scoping to the style object is a good idea.  

So, this removes the atomicness (atomicity?) of the media rules and rewrites them every time the parent object is updated.  It does a good job of maintaining order and handles the original case of media rules shared between components and modifying style objects between renders.  However, it does add some overhead of some extra hashes and always rewrites the media rules if the object is updated.

We might not care but I think it is still the case that a user could get an unexpected ordering if media rules are always rewritten but other items are not.  In this case the color will always be blue for the first render but if padding is updated then the object hash changes and the media query is pushed to the end and now applies.  

```js
{
  padding: 1,
  '@media (min-width: 52em)': {color: 'red'},
  color: blue,
}
```

Yes, this is a contrived example but this is a similar case that fails the 'all media rules in a separate sheet' example.  I think the only true solution to the above case is monolith writing the whole object.

Overall, I'm still trying to come up with cases where the extra overhead of computing hashes on the object and losing re-use of media rules is worthwhile over just sticking the media rules at the bottom.

**Comment by asilvas** [comment]
Effectivity this becomes a specificity vs ordering issue. The objective is to behave similar to that of pseudo classes, ala `:hover`, which work because of specificity. Media queries hold no greater specificity (which arguably is a flaw in media queries, but out of realm of this discussion). So to your point, we can solve it by way of order -- or by forcing specificity, which `!important` could do for us. That might be the lesser of evils to bring it more in line with pseudo classes.

The only use case I can think of where it would be be an issue is conflicting/overlapping media queries. But that seems more of an edge case than what we're solving for.

**Comment by asilvas** [comment]
@mihalik please create a PR with your fork. That seems like it might resolve the collisions. Have you done a fair bit of testing?

**Comment by mihalik** [comment]
@asilvas - I created #56.  This is the same code I linked previously.  I have used it in my application and is much better than my previous need to `!important` all my media rules.  I don't have any conflicting or overlapping media queries in my application so I'm not sure the behavior, but I imagine it is not any worse than the current behavior.
