### ISSUE TITLE
Sometimes appending `px` to a number breaks a property.

### ISSUE THREAD

**Issue by richard-lopes** [jxnblk/cxs#70]
For CSS rules, properties that can take a number, if you give a number a `px` will be appended automatically. It does work with common properties like `height`, `width`... But it adds unwanted `px` for `z-index` or `flex` for example.
We could document that a workaround to this is to use strings instead of numbers like so for those properties: `flex: '1'` or `zIndex: '1'` to prevent a `px` to be appended.

**Comment by lachlanjc** [comment]
The newest version fixes this 👍

**Comment by rlopes** [comment]
Should we close this issue then ?
